# Generated by Django 6.0.1 on 2026-02-01 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PC', 'Computador'), ('NB', 'Notebook')], default='NB', max_length=50)),
                ('modelo', models.CharField(help_text='Ex: Dell Inspiron, PC Gamer i5', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Serviço Realizado')),
                ('descricao', models.TextField(help_text='Detalhes do que foi feito.', verbose_name='Relatório Técnico')),
                ('data', models.DateField(auto_now_add=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.computador')),
            ],
        ),
    ]
