# Generated by Django 6.0.1 on 2026-02-05 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servico',
            name='computador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
