# Generated by Django 6.0.1 on 2026-02-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servico_cliente_alter_servico_computador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='nome_contato',
            field=models.CharField(default='Visitante', max_length=100),
        ),
    ]
