# Generated by Django 6.0.1 on 2026-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_codigovalidacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluido', 'Concluído')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='servico',
            name='computador',
            field=models.CharField(max_length=100, verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Problema'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Serviço'),
        ),
    ]
